# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ScShot.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScShot(object):
    def setupUi(self, ScShot):
        ScShot.setObjectName("ScShot")
        ScShot.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScShot.sizePolicy().hasHeightForWidth())
        ScShot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        ScShot.setFont(font)
        ScShot.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        ScShot.setMouseTracking(True)
        self.wTop = QtWidgets.QWidget(ScShot)
        self.wTop.setGeometry(QtCore.QRect(0, 0, 121, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wTop.sizePolicy().hasHeightForWidth())
        self.wTop.setSizePolicy(sizePolicy)
        self.wTop.setMouseTracking(True)
        self.wTop.setObjectName("wTop")
        self.wFunc = QtWidgets.QWidget(ScShot)
        self.wFunc.setGeometry(QtCore.QRect(110, 230, 175, 36))
        self.wFunc.setMinimumSize(QtCore.QSize(175, 36))
        self.wFunc.setMaximumSize(QtCore.QSize(175, 36))
        self.wFunc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wFunc.setObjectName("wFunc")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wFunc)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnBrush = QtWidgets.QPushButton(self.wFunc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBrush.sizePolicy().hasHeightForWidth())
        self.btnBrush.setSizePolicy(sizePolicy)
        self.btnBrush.setMaximumSize(QtCore.QSize(30, 30))
        self.btnBrush.setText("")
        self.btnBrush.setObjectName("btnBrush")
        self.horizontalLayout.addWidget(self.btnBrush)
        self.line_2 = QtWidgets.QFrame(self.wFunc)
        self.line_2.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.btnSaveAs = QtWidgets.QPushButton(self.wFunc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveAs.sizePolicy().hasHeightForWidth())
        self.btnSaveAs.setSizePolicy(sizePolicy)
        self.btnSaveAs.setMaximumSize(QtCore.QSize(30, 30))
        self.btnSaveAs.setText("")
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.horizontalLayout.addWidget(self.btnSaveAs)
        self.line = QtWidgets.QFrame(self.wFunc)
        self.line.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.btnNo = QtWidgets.QPushButton(self.wFunc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNo.sizePolicy().hasHeightForWidth())
        self.btnNo.setSizePolicy(sizePolicy)
        self.btnNo.setMaximumSize(QtCore.QSize(30, 30))
        self.btnNo.setText("")
        self.btnNo.setObjectName("btnNo")
        self.horizontalLayout.addWidget(self.btnNo)
        self.btnOk = QtWidgets.QPushButton(self.wFunc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOk.sizePolicy().hasHeightForWidth())
        self.btnOk.setSizePolicy(sizePolicy)
        self.btnOk.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btnOk.setFont(font)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.wInfo = QtWidgets.QWidget(ScShot)
        self.wInfo.setEnabled(True)
        self.wInfo.setGeometry(QtCore.QRect(260, 90, 122, 122))
        self.wInfo.setMinimumSize(QtCore.QSize(122, 122))
        self.wInfo.setMaximumSize(QtCore.QSize(122, 122))
        self.wInfo.setMouseTracking(True)
        self.wInfo.setObjectName("wInfo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wInfo)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wInfoZoomIn = QtWidgets.QWidget(self.wInfo)
        self.wInfoZoomIn.setMinimumSize(QtCore.QSize(120, 88))
        self.wInfoZoomIn.setMaximumSize(QtCore.QSize(120, 88))
        self.wInfoZoomIn.setMouseTracking(True)
        self.wInfoZoomIn.setObjectName("wInfoZoomIn")
        self.labRow = QtWidgets.QLabel(self.wInfoZoomIn)
        self.labRow.setGeometry(QtCore.QRect(2, 40, 116, 4))
        self.labRow.setMinimumSize(QtCore.QSize(116, 4))
        self.labRow.setMaximumSize(QtCore.QSize(116, 4))
        self.labRow.setMouseTracking(True)
        self.labRow.setText("")
        self.labRow.setObjectName("labRow")
        self.labColumn = QtWidgets.QLabel(self.wInfoZoomIn)
        self.labColumn.setGeometry(QtCore.QRect(56, 2, 4, 84))
        self.labColumn.setMinimumSize(QtCore.QSize(4, 84))
        self.labColumn.setMaximumSize(QtCore.QSize(4, 84))
        self.labColumn.setMouseTracking(True)
        self.labColumn.setText("")
        self.labColumn.setObjectName("labColumn")
        self.labInfoZoomIn = QtWidgets.QLabel(self.wInfoZoomIn)
        self.labInfoZoomIn.setGeometry(QtCore.QRect(2, 2, 116, 84))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labInfoZoomIn.sizePolicy().hasHeightForWidth())
        self.labInfoZoomIn.setSizePolicy(sizePolicy)
        self.labInfoZoomIn.setMinimumSize(QtCore.QSize(116, 84))
        self.labInfoZoomIn.setMaximumSize(QtCore.QSize(116, 84))
        self.labInfoZoomIn.setText("")
        self.labInfoZoomIn.setScaledContents(True)
        self.labInfoZoomIn.setObjectName("labInfoZoomIn")
        self.labInfoZoomIn.raise_()
        self.labRow.raise_()
        self.labColumn.raise_()
        self.verticalLayout.addWidget(self.wInfoZoomIn)
        self.textEdInfoRgb = QtWidgets.QTextEdit(self.wInfo)
        self.textEdInfoRgb.setEnabled(False)
        self.textEdInfoRgb.setMinimumSize(QtCore.QSize(120, 32))
        self.textEdInfoRgb.setMaximumSize(QtCore.QSize(120, 32))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setBold(False)
        font.setWeight(50)
        self.textEdInfoRgb.setFont(font)
        self.textEdInfoRgb.setMouseTracking(True)
        self.textEdInfoRgb.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdInfoRgb.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdInfoRgb.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdInfoRgb.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdInfoRgb.setLineWrapColumnOrWidth(0)
        self.textEdInfoRgb.setReadOnly(True)
        self.textEdInfoRgb.setObjectName("textEdInfoRgb")
        self.verticalLayout.addWidget(self.textEdInfoRgb)

        self.retranslateUi(ScShot)
        self.btnOk.clicked.connect(ScShot.close)
        self.btnNo.clicked.connect(ScShot.close)
        QtCore.QMetaObject.connectSlotsByName(ScShot)

    def retranslateUi(self, ScShot):
        _translate = QtCore.QCoreApplication.translate
        ScShot.setWindowTitle(_translate("ScShot", "Form"))
        self.btnBrush.setToolTip(_translate("ScShot", "画笔"))
        self.btnSaveAs.setToolTip(_translate("ScShot", "另存为"))
        self.btnNo.setToolTip(_translate("ScShot", "取消"))
        self.btnNo.setShortcut(_translate("ScShot", "Esc"))
        self.btnOk.setText(_translate("ScShot", "完成"))
        self.btnOk.setShortcut(_translate("ScShot", "Return"))
        self.textEdInfoRgb.setHtml(_translate("ScShot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'方正姚体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

