# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ChatSocket.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatSocket(object):
    def setupUi(self, ChatSocket):
        ChatSocket.setObjectName("ChatSocket")
        ChatSocket.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChatSocket)
        self.verticalLayout.setObjectName("verticalLayout")
        self.recv_textEdit = QtWidgets.QTextEdit(ChatSocket)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.recv_textEdit.setFont(font)
        self.recv_textEdit.setStyleSheet("color: rgb(0, 0, 195);")
        self.recv_textEdit.setObjectName("recv_textEdit")
        self.verticalLayout.addWidget(self.recv_textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ChatSocket)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ipLineEdit = QtWidgets.QLineEdit(ChatSocket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipLineEdit.sizePolicy().hasHeightForWidth())
        self.ipLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ipLineEdit.setFont(font)
        self.ipLineEdit.setStyleSheet("color: rgb(195, 0, 0);")
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.horizontalLayout.addWidget(self.ipLineEdit)
        self.label_2 = QtWidgets.QLabel(ChatSocket)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.portLineEdit = QtWidgets.QLineEdit(ChatSocket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.portLineEdit.setFont(font)
        self.portLineEdit.setStyleSheet("color: rgb(195, 0, 0);")
        self.portLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.portLineEdit.setMaxLength(5)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout.addWidget(self.portLineEdit)
        self.btnServer = QtWidgets.QPushButton(ChatSocket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnServer.sizePolicy().hasHeightForWidth())
        self.btnServer.setSizePolicy(sizePolicy)
        self.btnServer.setStyleSheet("color: rgb(255, 0, 0);")
        self.btnServer.setObjectName("btnServer")
        self.horizontalLayout.addWidget(self.btnServer)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 3)
        self.horizontalLayout.setStretch(4, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.send_textEdit = QtWidgets.QTextEdit(ChatSocket)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.send_textEdit.setFont(font)
        self.send_textEdit.setObjectName("send_textEdit")
        self.verticalLayout.addWidget(self.send_textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnSend = QtWidgets.QPushButton(ChatSocket)
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout_2.addWidget(self.btnSend)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(ChatSocket)
        QtCore.QMetaObject.connectSlotsByName(ChatSocket)

    def retranslateUi(self, ChatSocket):
        _translate = QtCore.QCoreApplication.translate
        ChatSocket.setWindowTitle(_translate("ChatSocket", "聊天服务器"))
        self.label.setText(_translate("ChatSocket", "IP:"))
        self.ipLineEdit.setInputMask(_translate("ChatSocket", "000.000.000.000"))
        self.label_2.setText(_translate("ChatSocket", "PORT:"))
        self.btnServer.setText(_translate("ChatSocket", "启动服务器"))
        self.btnSend.setText(_translate("ChatSocket", "发送"))
