# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(14)
        Main.setFont(font)
        Main.setStyleSheet("QWidget#Main {border-image: url(:/bg1.jpg);}\n"
"QWidget#Main QPushButton:hover {background: rgba(255, 255, 255, 50);}\n"
"QWidget#Main QPushButton:pressed {padding-top:5px;padding-left:5px;}\n"
"\n"
"QWidget#widget_4 QPushButton {background: rgba(0, 0, 0, 50);border-radius:5px;}\n"
"\n"
"QPushButton#btnOrder {background: rgba(0, 0, 0, 50);border-radius:20px;border-image: url(:/bg6.png);color:red;}\n"
"\n"
"QWidget#Main QPushButton#btnUnpaid {color: rgb(75, 250, 0);}\n"
"QWidget#Main QPushButton#btnPaid {color: rgb(205, 0, 0);}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Main)
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(Main)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.btnTodayDish = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTodayDish.sizePolicy().hasHeightForWidth())
        self.btnTodayDish.setSizePolicy(sizePolicy)
        self.btnTodayDish.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.btnTodayDish.setFont(font)
        self.btnTodayDish.setObjectName("btnTodayDish")
        self.gridLayout.addWidget(self.btnTodayDish, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.btnUnpaid = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUnpaid.sizePolicy().hasHeightForWidth())
        self.btnUnpaid.setSizePolicy(sizePolicy)
        self.btnUnpaid.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.btnUnpaid.setFont(font)
        self.btnUnpaid.setStyleSheet("")
        self.btnUnpaid.setObjectName("btnUnpaid")
        self.gridLayout.addWidget(self.btnUnpaid, 1, 0, 1, 1)
        self.btnPaid = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPaid.sizePolicy().hasHeightForWidth())
        self.btnPaid.setSizePolicy(sizePolicy)
        self.btnPaid.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.btnPaid.setFont(font)
        self.btnPaid.setStyleSheet("")
        self.btnPaid.setObjectName("btnPaid")
        self.gridLayout.addWidget(self.btnPaid, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.widget_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnOrder = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOrder.sizePolicy().hasHeightForWidth())
        self.btnOrder.setSizePolicy(sizePolicy)
        self.btnOrder.setMinimumSize(QtCore.QSize(200, 80))
        self.btnOrder.setMaximumSize(QtCore.QSize(200, 80))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(27)
        self.btnOrder.setFont(font)
        self.btnOrder.setStyleSheet("")
        self.btnOrder.setObjectName("btnOrder")
        self.horizontalLayout_3.addWidget(self.btnOrder)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Main)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stkWid = QtWidgets.QStackedWidget(self.widget_2)
        self.stkWid.setObjectName("stkWid")
        self.widUnpaid = QtWidgets.QWidget()
        self.widUnpaid.setObjectName("widUnpaid")
        self.gridUnpaid = QtWidgets.QGridLayout(self.widUnpaid)
        self.gridUnpaid.setContentsMargins(0, 0, 0, 0)
        self.gridUnpaid.setObjectName("gridUnpaid")
        self.stkWid.addWidget(self.widUnpaid)
        self.widPaid = QtWidgets.QWidget()
        self.widPaid.setObjectName("widPaid")
        self.gridPaid = QtWidgets.QGridLayout(self.widPaid)
        self.gridPaid.setContentsMargins(0, 0, 0, 0)
        self.gridPaid.setObjectName("gridPaid")
        self.stkWid.addWidget(self.widPaid)
        self.horizontalLayout_2.addWidget(self.stkWid)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Main)
        self.stkWid.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "枫林苑农庄——营业管理系统1.0版"))
        self.label.setText(_translate("Main", "<html><head/><body><p><span style=\" color:#de0000;\">枫林苑农庄</span>欢迎新老顾客</p></body></html>"))
        self.btnTodayDish.setText(_translate("Main", "今日菜谱"))
        self.pushButton_5.setText(_translate("Main", "统计"))
        self.btnUnpaid.setText(_translate("Main", "未结账"))
        self.btnPaid.setText(_translate("Main", "已结账"))
        self.btnOrder.setText(_translate("Main", "新客点餐"))

import images_rc
