# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_NewGuests.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewGuests(object):
    def setupUi(self, NewGuests):
        NewGuests.setObjectName("NewGuests")
        NewGuests.resize(760, 600)
        NewGuests.setMinimumSize(QtCore.QSize(760, 600))
        NewGuests.setMaximumSize(QtCore.QSize(760, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        NewGuests.setFont(font)
        NewGuests.setStyleSheet("\n"
"QWidget#NewGuests {border-image: url(:/bg2.jpg);}\n"
"QWidget#NewGuests QTabWidget:pane {border: none;}\n"
"QWidget#NewGuests QTabBar:tab {background:transparent;border-radius:3px;width:80;}\n"
"QWidget#NewGuests QTabBar:tab:hover {background: rgba(0,0,0,50);}\n"
"QWidget#NewGuests QTabBar:tab:selected {background: rgba(0,0,0,50);}\n"
"\n"
"QTableWidget {border-image: url(:/bg4.jpg);alternate-background-color: rgba(0, 0, 0, 20);}\n"
"QTableWidget::item:selected {background-color: lightgreen;}\n"
"\n"
"\n"
"QPushButton {background: rgba(255, 255, 255, 50);border-radius:5px;}\n"
"QPushButton:hover {background: rgba(0, 0, 0, 50);}\n"
"\n"
"")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(NewGuests)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_3 = QtWidgets.QWidget(NewGuests)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setMinimumSize(QtCore.QSize(90, 80))
        self.label.setMaximumSize(QtCore.QSize(90, 80))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labDeskName = QtWidgets.QLabel(self.widget_3)
        self.labDeskName.setMinimumSize(QtCore.QSize(0, 80))
        self.labDeskName.setMaximumSize(QtCore.QSize(1111, 80))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(33)
        self.labDeskName.setFont(font)
        self.labDeskName.setStyleSheet("color: rgb(222, 0, 0);")
        self.labDeskName.setAlignment(QtCore.Qt.AlignCenter)
        self.labDeskName.setObjectName("labDeskName")
        self.horizontalLayout.addWidget(self.labDeskName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.btnChangeDesk = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnChangeDesk.sizePolicy().hasHeightForWidth())
        self.btnChangeDesk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.btnChangeDesk.setFont(font)
        self.btnChangeDesk.setObjectName("btnChangeDesk")
        self.horizontalLayout.addWidget(self.btnChangeDesk)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(NewGuests)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_4)
        self.tabWidget.setMinimumSize(QtCore.QSize(320, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(23)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidColdDish3 = QtWidgets.QWidget()
        self.tabWidColdDish3.setObjectName("tabWidColdDish3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabWidColdDish3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidColdDish3 = QtWidgets.QTableWidget(self.tabWidColdDish3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidColdDish3.setFont(font)
        self.tableWidColdDish3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidColdDish3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidColdDish3.setAlternatingRowColors(True)
        self.tableWidColdDish3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidColdDish3.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidColdDish3.setObjectName("tableWidColdDish3")
        self.tableWidColdDish3.setColumnCount(2)
        self.tableWidColdDish3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidColdDish3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidColdDish3.setHorizontalHeaderItem(1, item)
        self.tableWidColdDish3.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidColdDish3)
        self.tabWidget.addTab(self.tabWidColdDish3, "")
        self.tabWidHotDishes3 = QtWidgets.QWidget()
        self.tabWidHotDishes3.setObjectName("tabWidHotDishes3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabWidHotDishes3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidHotDishes3 = QtWidgets.QTableWidget(self.tabWidHotDishes3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidHotDishes3.setFont(font)
        self.tableWidHotDishes3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidHotDishes3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidHotDishes3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidHotDishes3.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidHotDishes3.setObjectName("tableWidHotDishes3")
        self.tableWidHotDishes3.setColumnCount(2)
        self.tableWidHotDishes3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidHotDishes3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidHotDishes3.setHorizontalHeaderItem(1, item)
        self.tableWidHotDishes3.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidHotDishes3)
        self.tabWidget.addTab(self.tabWidHotDishes3, "")
        self.tabWidDrinks3 = QtWidgets.QWidget()
        self.tabWidDrinks3.setObjectName("tabWidDrinks3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabWidDrinks3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidDrinks3 = QtWidgets.QTableWidget(self.tabWidDrinks3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidDrinks3.setFont(font)
        self.tableWidDrinks3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidDrinks3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidDrinks3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidDrinks3.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidDrinks3.setObjectName("tableWidDrinks3")
        self.tableWidDrinks3.setColumnCount(2)
        self.tableWidDrinks3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidDrinks3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidDrinks3.setHorizontalHeaderItem(1, item)
        self.tableWidDrinks3.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.tableWidDrinks3)
        self.tabWidget.addTab(self.tabWidDrinks3, "")
        self.tabWidOther3 = QtWidgets.QWidget()
        self.tabWidOther3.setObjectName("tabWidOther3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabWidOther3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidOther3 = QtWidgets.QTableWidget(self.tabWidOther3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidOther3.setFont(font)
        self.tableWidOther3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidOther3.setStyleSheet("")
        self.tableWidOther3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidOther3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidOther3.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidOther3.setObjectName("tableWidOther3")
        self.tableWidOther3.setColumnCount(2)
        self.tableWidOther3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOther3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOther3.setHorizontalHeaderItem(1, item)
        self.tableWidOther3.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.tableWidOther3)
        self.tabWidget.addTab(self.tabWidOther3, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidOrderDish = QtWidgets.QTableWidget(self.widget)
        self.tableWidOrderDish.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidOrderDish.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.tableWidOrderDish.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidOrderDish.setStyleSheet("")
        self.tableWidOrderDish.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidOrderDish.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidOrderDish.setAlternatingRowColors(True)
        self.tableWidOrderDish.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidOrderDish.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidOrderDish.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidOrderDish.setObjectName("tableWidOrderDish")
        self.tableWidOrderDish.setColumnCount(4)
        self.tableWidOrderDish.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOrderDish.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOrderDish.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOrderDish.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOrderDish.setHorizontalHeaderItem(3, item)
        self.tableWidOrderDish.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidOrderDish.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidOrderDish.horizontalHeader().setStretchLastSection(True)
        self.tableWidOrderDish.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout.addWidget(self.tableWidOrderDish, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.widget_2)
        self.btnAdd.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.btnDel = QtWidgets.QPushButton(self.widget_2)
        self.btnDel.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        self.btnDel.setFont(font)
        self.btnDel.setObjectName("btnDel")
        self.verticalLayout.addWidget(self.btnDel)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.btnTodayDishShow = QtWidgets.QPushButton(self.widget_2)
        self.btnTodayDishShow.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        self.btnTodayDishShow.setFont(font)
        self.btnTodayDishShow.setObjectName("btnTodayDishShow")
        self.verticalLayout.addWidget(self.btnTodayDishShow)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(206, 68, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(NewGuests)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_5.setObjectName("widget_5")
        self.btnWait = QtWidgets.QPushButton(self.widget_5)
        self.btnWait.setGeometry(QtCore.QRect(253, 2, 180, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWait.sizePolicy().hasHeightForWidth())
        self.btnWait.setSizePolicy(sizePolicy)
        self.btnWait.setMinimumSize(QtCore.QSize(0, 46))
        self.btnWait.setMaximumSize(QtCore.QSize(180, 46))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.btnWait.setFont(font)
        self.btnWait.setStyleSheet("color: rgb(0, 66, 200);")
        self.btnWait.setObjectName("btnWait")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setGeometry(QtCore.QRect(613, 2, 135, 46))
        self.widget_6.setMinimumSize(QtCore.QSize(0, 46))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        self.widget_6.setFont(font)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labWhetherPay = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.labWhetherPay.setFont(font)
        self.labWhetherPay.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labWhetherPay.setObjectName("labWhetherPay")
        self.horizontalLayout_4.addWidget(self.labWhetherPay)
        self.labTotalMoney = QtWidgets.QLabel(self.widget_6)
        self.labTotalMoney.setMinimumSize(QtCore.QSize(70, 0))
        self.labTotalMoney.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labTotalMoney.setFont(font)
        self.labTotalMoney.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius:10px;\n"
"")
        self.labTotalMoney.setAlignment(QtCore.Qt.AlignCenter)
        self.labTotalMoney.setObjectName("labTotalMoney")
        self.horizontalLayout_4.addWidget(self.labTotalMoney)
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.btnPay = QtWidgets.QPushButton(self.widget_5)
        self.btnPay.setGeometry(QtCore.QRect(433, 2, 180, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPay.sizePolicy().hasHeightForWidth())
        self.btnPay.setSizePolicy(sizePolicy)
        self.btnPay.setMinimumSize(QtCore.QSize(180, 46))
        self.btnPay.setMaximumSize(QtCore.QSize(180, 46))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.btnPay.setFont(font)
        self.btnPay.setStyleSheet("color: rgb(218, 0, 0);")
        self.btnPay.setObjectName("btnPay")
        self.btnQuit = QtWidgets.QPushButton(self.widget_5)
        self.btnQuit.setGeometry(QtCore.QRect(2, 2, 111, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnQuit.sizePolicy().hasHeightForWidth())
        self.btnQuit.setSizePolicy(sizePolicy)
        self.btnQuit.setMinimumSize(QtCore.QSize(0, 46))
        self.btnQuit.setMaximumSize(QtCore.QSize(180, 46))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.btnQuit.setFont(font)
        self.btnQuit.setStyleSheet("color: rgb(0, 0, 0);")
        self.btnQuit.setObjectName("btnQuit")
        self.verticalLayout_5.addWidget(self.widget_5)

        self.retranslateUi(NewGuests)
        self.tabWidget.setCurrentIndex(0)
        self.btnQuit.clicked.connect(NewGuests.close)
        QtCore.QMetaObject.connectSlotsByName(NewGuests)

    def retranslateUi(self, NewGuests):
        _translate = QtCore.QCoreApplication.translate
        NewGuests.setWindowTitle(_translate("NewGuests", "枫林苑农庄——新客点餐"))
        self.label.setText(_translate("NewGuests", "桌号："))
        self.labDeskName.setText(_translate("NewGuests", "未知"))
        self.btnChangeDesk.setText(_translate("NewGuests", "更改\n"
"桌号"))
        item = self.tableWidColdDish3.horizontalHeaderItem(0)
        item.setText(_translate("NewGuests", "菜名"))
        item = self.tableWidColdDish3.horizontalHeaderItem(1)
        item.setText(_translate("NewGuests", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidColdDish3), _translate("NewGuests", "凉菜"))
        item = self.tableWidHotDishes3.horizontalHeaderItem(0)
        item.setText(_translate("NewGuests", "菜名"))
        item = self.tableWidHotDishes3.horizontalHeaderItem(1)
        item.setText(_translate("NewGuests", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidHotDishes3), _translate("NewGuests", "热菜"))
        item = self.tableWidDrinks3.horizontalHeaderItem(0)
        item.setText(_translate("NewGuests", "菜名"))
        item = self.tableWidDrinks3.horizontalHeaderItem(1)
        item.setText(_translate("NewGuests", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidDrinks3), _translate("NewGuests", "酒水"))
        item = self.tableWidOther3.horizontalHeaderItem(0)
        item.setText(_translate("NewGuests", "种类"))
        item = self.tableWidOther3.horizontalHeaderItem(1)
        item.setText(_translate("NewGuests", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidOther3), _translate("NewGuests", "其它"))
        self.tableWidOrderDish.setSortingEnabled(True)
        item = self.tableWidOrderDish.horizontalHeaderItem(0)
        item.setText(_translate("NewGuests", "类型"))
        item = self.tableWidOrderDish.horizontalHeaderItem(1)
        item.setText(_translate("NewGuests", "菜名"))
        item = self.tableWidOrderDish.horizontalHeaderItem(2)
        item.setText(_translate("NewGuests", "单价"))
        item = self.tableWidOrderDish.horizontalHeaderItem(3)
        item.setText(_translate("NewGuests", "数量"))
        self.btnAdd.setText(_translate("NewGuests", ">\n"
"添加"))
        self.btnDel.setText(_translate("NewGuests", "<\n"
"删除"))
        self.btnTodayDishShow.setText(_translate("NewGuests", "编辑\n"
"菜谱"))
        self.label_3.setText(_translate("NewGuests", "客人菜单"))
        self.btnWait.setText(_translate("NewGuests", "等待客人用餐"))
        self.labWhetherPay.setText(_translate("NewGuests", "未结账"))
        self.labTotalMoney.setText(_translate("NewGuests", "5555"))
        self.label_6.setText(_translate("NewGuests", "元"))
        self.btnPay.setText(_translate("NewGuests", "客人结账"))
        self.btnQuit.setText(_translate("NewGuests", "关闭"))

import images_rc
