# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_TodayDish.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TodayDish(object):
    def setupUi(self, TodayDish):
        TodayDish.setObjectName("TodayDish")
        TodayDish.resize(735, 600)
        TodayDish.setMinimumSize(QtCore.QSize(0, 600))
        TodayDish.setMaximumSize(QtCore.QSize(735, 600))
        TodayDish.setStyleSheet("QWidget#TodayDish QTabBar:tab {background:transparent;border-radius:3px;width:80;}\n"
"QWidget#TodayDish {border-image: url(:/bg5.jpg);}\n"
"QWidget#TodayDish QTabBar:tab:hover {background: rgba(255, 255, 255, 100);}\n"
"QWidget#TodayDish QTabBar:tab:selected {background:rgba(255, 255, 255, 100);}\n"
"\n"
"QTableWidget {border-image: url(:/bg3.jpg);alternate-background-color: rgba(255, 255, 255, 80);}\n"
"\n"
"QPushButton {background: transparent;border-radius:5px;}\n"
"QPushButton:hover {background: rgba(255, 255, 255, 100);}")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(TodayDish)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_4 = QtWidgets.QWidget(TodayDish)
        self.widget_4.setMinimumSize(QtCore.QSize(405, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(23)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabColdDish = QtWidgets.QWidget()
        self.tabColdDish.setObjectName("tabColdDish")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabColdDish)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidColdDish = QtWidgets.QTableWidget(self.tabColdDish)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.tableWidColdDish.setFont(font)
        self.tableWidColdDish.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidColdDish.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidColdDish.setAlternatingRowColors(True)
        self.tableWidColdDish.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidColdDish.setObjectName("tableWidColdDish")
        self.tableWidColdDish.setColumnCount(2)
        self.tableWidColdDish.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidColdDish.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidColdDish.setHorizontalHeaderItem(1, item)
        self.tableWidColdDish.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidColdDish.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidColdDish.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidColdDish.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidColdDish.horizontalHeader().setStretchLastSection(True)
        self.tableWidColdDish.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableWidColdDish)
        self.tabWidget.addTab(self.tabColdDish, "")
        self.tabHotDishes = QtWidgets.QWidget()
        self.tabHotDishes.setObjectName("tabHotDishes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabHotDishes)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidHotDishes = QtWidgets.QTableWidget(self.tabHotDishes)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.tableWidHotDishes.setFont(font)
        self.tableWidHotDishes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidHotDishes.setAlternatingRowColors(True)
        self.tableWidHotDishes.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidHotDishes.setObjectName("tableWidHotDishes")
        self.tableWidHotDishes.setColumnCount(2)
        self.tableWidHotDishes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidHotDishes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidHotDishes.setHorizontalHeaderItem(1, item)
        self.tableWidHotDishes.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidHotDishes)
        self.tabWidget.addTab(self.tabHotDishes, "")
        self.tabDrinks = QtWidgets.QWidget()
        self.tabDrinks.setObjectName("tabDrinks")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabDrinks)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidDrinks = QtWidgets.QTableWidget(self.tabDrinks)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.tableWidDrinks.setFont(font)
        self.tableWidDrinks.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidDrinks.setAlternatingRowColors(True)
        self.tableWidDrinks.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidDrinks.setObjectName("tableWidDrinks")
        self.tableWidDrinks.setColumnCount(2)
        self.tableWidDrinks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidDrinks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidDrinks.setHorizontalHeaderItem(1, item)
        self.tableWidDrinks.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.tableWidDrinks)
        self.tabWidget.addTab(self.tabDrinks, "")
        self.tabOther = QtWidgets.QWidget()
        self.tabOther.setObjectName("tabOther")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabOther)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidOther = QtWidgets.QTableWidget(self.tabOther)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.tableWidOther.setFont(font)
        self.tableWidOther.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidOther.setAlternatingRowColors(True)
        self.tableWidOther.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidOther.setObjectName("tableWidOther")
        self.tableWidOther.setColumnCount(2)
        self.tableWidOther.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOther.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOther.setHorizontalHeaderItem(1, item)
        self.tableWidOther.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.tableWidOther)
        self.tabWidget.addTab(self.tabOther, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.widBtnGroup = QtWidgets.QWidget(self.widget_3)
        self.widBtnGroup.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.widBtnGroup.setFont(font)
        self.widBtnGroup.setObjectName("widBtnGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widBtnGroup)
        self.verticalLayout_5.setContentsMargins(0, 60, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnAddRow = QtWidgets.QPushButton(self.widBtnGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddRow.sizePolicy().hasHeightForWidth())
        self.btnAddRow.setSizePolicy(sizePolicy)
        self.btnAddRow.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnAddRow.setFont(font)
        self.btnAddRow.setObjectName("btnAddRow")
        self.verticalLayout_5.addWidget(self.btnAddRow)
        self.btnDelRow = QtWidgets.QPushButton(self.widBtnGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelRow.sizePolicy().hasHeightForWidth())
        self.btnDelRow.setSizePolicy(sizePolicy)
        self.btnDelRow.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnDelRow.setFont(font)
        self.btnDelRow.setObjectName("btnDelRow")
        self.verticalLayout_5.addWidget(self.btnDelRow)
        self.btnMoveUp = QtWidgets.QPushButton(self.widBtnGroup)
        self.btnMoveUp.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnMoveUp.setFont(font)
        self.btnMoveUp.setObjectName("btnMoveUp")
        self.verticalLayout_5.addWidget(self.btnMoveUp)
        self.btnMoveDn = QtWidgets.QPushButton(self.widBtnGroup)
        self.btnMoveDn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnMoveDn.setFont(font)
        self.btnMoveDn.setObjectName("btnMoveDn")
        self.verticalLayout_5.addWidget(self.btnMoveDn)
        self.btnAllDish = QtWidgets.QPushButton(self.widBtnGroup)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnAllDish.setFont(font)
        self.btnAllDish.setObjectName("btnAllDish")
        self.verticalLayout_5.addWidget(self.btnAllDish)
        self.btnOldDish = QtWidgets.QPushButton(self.widBtnGroup)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnOldDish.setFont(font)
        self.btnOldDish.setObjectName("btnOldDish")
        self.verticalLayout_5.addWidget(self.btnOldDish)
        self.horizontalLayout.addWidget(self.widBtnGroup)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(405, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSave = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setMinimumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("color: rgb(0, 150, 0);")
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setMinimumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("color: rgb(178, 0, 0);")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.widAllDish = QtWidgets.QWidget(TodayDish)
        self.widAllDish.setMinimumSize(QtCore.QSize(0, 0))
        self.widAllDish.setObjectName("widAllDish")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widAllDish)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.widAllDish)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(61, 61, 184);\n"
"color: rgb(192, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.widAllDish)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(23)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabColdDish2 = QtWidgets.QWidget()
        self.tabColdDish2.setObjectName("tabColdDish2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabColdDish2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidColdDish2 = QtWidgets.QTableWidget(self.tabColdDish2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidColdDish2.setFont(font)
        self.tableWidColdDish2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidColdDish2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidColdDish2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidColdDish2.setAlternatingRowColors(True)
        self.tableWidColdDish2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidColdDish2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidColdDish2.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidColdDish2.setObjectName("tableWidColdDish2")
        self.tableWidColdDish2.setColumnCount(2)
        self.tableWidColdDish2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidColdDish2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidColdDish2.setHorizontalHeaderItem(1, item)
        self.tableWidColdDish2.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidColdDish2.horizontalHeader().setMinimumSectionSize(25)
        self.verticalLayout_7.addWidget(self.tableWidColdDish2)
        self.tabWidget_2.addTab(self.tabColdDish2, "")
        self.tabHotDishes2 = QtWidgets.QWidget()
        self.tabHotDishes2.setObjectName("tabHotDishes2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabHotDishes2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidHotDishes2 = QtWidgets.QTableWidget(self.tabHotDishes2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidHotDishes2.setFont(font)
        self.tableWidHotDishes2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidHotDishes2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidHotDishes2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidHotDishes2.setAlternatingRowColors(True)
        self.tableWidHotDishes2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidHotDishes2.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidHotDishes2.setObjectName("tableWidHotDishes2")
        self.tableWidHotDishes2.setColumnCount(2)
        self.tableWidHotDishes2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidHotDishes2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidHotDishes2.setHorizontalHeaderItem(1, item)
        self.verticalLayout_8.addWidget(self.tableWidHotDishes2)
        self.tabWidget_2.addTab(self.tabHotDishes2, "")
        self.tabDrinks2 = QtWidgets.QWidget()
        self.tabDrinks2.setObjectName("tabDrinks2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabDrinks2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableWidDrinks2 = QtWidgets.QTableWidget(self.tabDrinks2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidDrinks2.setFont(font)
        self.tableWidDrinks2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidDrinks2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidDrinks2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidDrinks2.setAlternatingRowColors(True)
        self.tableWidDrinks2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidDrinks2.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidDrinks2.setObjectName("tableWidDrinks2")
        self.tableWidDrinks2.setColumnCount(2)
        self.tableWidDrinks2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidDrinks2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidDrinks2.setHorizontalHeaderItem(1, item)
        self.verticalLayout_9.addWidget(self.tableWidDrinks2)
        self.tabWidget_2.addTab(self.tabDrinks2, "")
        self.tabOther2 = QtWidgets.QWidget()
        self.tabOther2.setObjectName("tabOther2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabOther2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableWidOther2 = QtWidgets.QTableWidget(self.tabOther2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidOther2.setFont(font)
        self.tableWidOther2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidOther2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidOther2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidOther2.setAlternatingRowColors(True)
        self.tableWidOther2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidOther2.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidOther2.setObjectName("tableWidOther2")
        self.tableWidOther2.setColumnCount(2)
        self.tableWidOther2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOther2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidOther2.setHorizontalHeaderItem(1, item)
        self.verticalLayout_10.addWidget(self.tableWidOther2)
        self.tabWidget_2.addTab(self.tabOther2, "")
        self.verticalLayout_11.addWidget(self.tabWidget_2)
        self.horizontalLayout_3.addWidget(self.widAllDish)

        self.retranslateUi(TodayDish)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.btnCancel.clicked.connect(TodayDish.close)
        QtCore.QMetaObject.connectSlotsByName(TodayDish)

    def retranslateUi(self, TodayDish):
        _translate = QtCore.QCoreApplication.translate
        TodayDish.setWindowTitle(_translate("TodayDish", "枫林苑农庄——今日菜谱"))
        item = self.tableWidColdDish.horizontalHeaderItem(0)
        item.setText(_translate("TodayDish", "菜名"))
        item = self.tableWidColdDish.horizontalHeaderItem(1)
        item.setText(_translate("TodayDish", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabColdDish), _translate("TodayDish", "凉菜"))
        item = self.tableWidHotDishes.horizontalHeaderItem(0)
        item.setText(_translate("TodayDish", "菜名"))
        item = self.tableWidHotDishes.horizontalHeaderItem(1)
        item.setText(_translate("TodayDish", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHotDishes), _translate("TodayDish", "热菜"))
        item = self.tableWidDrinks.horizontalHeaderItem(0)
        item.setText(_translate("TodayDish", "种类"))
        item = self.tableWidDrinks.horizontalHeaderItem(1)
        item.setText(_translate("TodayDish", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDrinks), _translate("TodayDish", "酒水"))
        item = self.tableWidOther.horizontalHeaderItem(0)
        item.setText(_translate("TodayDish", "种类"))
        item = self.tableWidOther.horizontalHeaderItem(1)
        item.setText(_translate("TodayDish", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOther), _translate("TodayDish", "其它"))
        self.btnAddRow.setText(_translate("TodayDish", "添加行"))
        self.btnDelRow.setText(_translate("TodayDish", "删除行"))
        self.btnMoveUp.setText(_translate("TodayDish", "上移"))
        self.btnMoveDn.setText(_translate("TodayDish", "下移"))
        self.btnAllDish.setText(_translate("TodayDish", "显示历史\n"
"全部菜谱"))
        self.btnOldDish.setText(_translate("TodayDish", "导入历史\n"
"菜谱日期"))
        self.btnSave.setText(_translate("TodayDish", "保存"))
        self.btnCancel.setText(_translate("TodayDish", "取消"))
        self.label.setText(_translate("TodayDish", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">历史全部菜谱</span><span style=\" vertical-align:sub;\">双击快速添加</span></p></body></html>"))
        item = self.tableWidColdDish2.horizontalHeaderItem(0)
        item.setText(_translate("TodayDish", "菜名"))
        item = self.tableWidColdDish2.horizontalHeaderItem(1)
        item.setText(_translate("TodayDish", "价格"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabColdDish2), _translate("TodayDish", "凉菜"))
        item = self.tableWidHotDishes2.horizontalHeaderItem(0)
        item.setText(_translate("TodayDish", "菜名"))
        item = self.tableWidHotDishes2.horizontalHeaderItem(1)
        item.setText(_translate("TodayDish", "价格"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabHotDishes2), _translate("TodayDish", "热菜"))
        item = self.tableWidDrinks2.horizontalHeaderItem(0)
        item.setText(_translate("TodayDish", "种类"))
        item = self.tableWidDrinks2.horizontalHeaderItem(1)
        item.setText(_translate("TodayDish", "价格"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabDrinks2), _translate("TodayDish", "酒水"))
        item = self.tableWidOther2.horizontalHeaderItem(0)
        item.setText(_translate("TodayDish", "种类"))
        item = self.tableWidOther2.horizontalHeaderItem(1)
        item.setText(_translate("TodayDish", "价格"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabOther2), _translate("TodayDish", "其它"))

import images_rc
