# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuKeyBoard.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_menuKeyBoard(object):
    def setupUi(self, menuKeyBoard):
        menuKeyBoard.setObjectName("menuKeyBoard")
        menuKeyBoard.resize(415, 110)
        menuKeyBoard.setMaximumSize(QtCore.QSize(415, 110))
        self.verticalLayout = QtWidgets.QVBoxLayout(menuKeyBoard)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_15 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_15.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout.addWidget(self.pushButton_15)
        self.key_1 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_1.setMinimumSize(QtCore.QSize(0, 0))
        self.key_1.setMaximumSize(QtCore.QSize(25, 25))
        self.key_1.setObjectName("key_1")
        self.horizontalLayout.addWidget(self.key_1)
        self.key_2 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_2.setMinimumSize(QtCore.QSize(0, 0))
        self.key_2.setMaximumSize(QtCore.QSize(25, 25))
        self.key_2.setObjectName("key_2")
        self.horizontalLayout.addWidget(self.key_2)
        self.key_3 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_3.setMinimumSize(QtCore.QSize(0, 0))
        self.key_3.setMaximumSize(QtCore.QSize(25, 25))
        self.key_3.setObjectName("key_3")
        self.horizontalLayout.addWidget(self.key_3)
        self.key_4 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_4.setMinimumSize(QtCore.QSize(0, 0))
        self.key_4.setMaximumSize(QtCore.QSize(25, 25))
        self.key_4.setObjectName("key_4")
        self.horizontalLayout.addWidget(self.key_4)
        self.key_5 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_5.setMinimumSize(QtCore.QSize(0, 0))
        self.key_5.setMaximumSize(QtCore.QSize(25, 25))
        self.key_5.setObjectName("key_5")
        self.horizontalLayout.addWidget(self.key_5)
        self.key_6 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_6.setMinimumSize(QtCore.QSize(0, 0))
        self.key_6.setMaximumSize(QtCore.QSize(25, 25))
        self.key_6.setObjectName("key_6")
        self.horizontalLayout.addWidget(self.key_6)
        self.key_7 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_7.setMinimumSize(QtCore.QSize(0, 0))
        self.key_7.setMaximumSize(QtCore.QSize(25, 25))
        self.key_7.setObjectName("key_7")
        self.horizontalLayout.addWidget(self.key_7)
        self.key_8 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_8.setMinimumSize(QtCore.QSize(0, 0))
        self.key_8.setMaximumSize(QtCore.QSize(25, 25))
        self.key_8.setObjectName("key_8")
        self.horizontalLayout.addWidget(self.key_8)
        self.key_9 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_9.setMinimumSize(QtCore.QSize(0, 0))
        self.key_9.setMaximumSize(QtCore.QSize(25, 25))
        self.key_9.setObjectName("key_9")
        self.horizontalLayout.addWidget(self.key_9)
        self.key_0 = QtWidgets.QPushButton(menuKeyBoard)
        self.key_0.setMinimumSize(QtCore.QSize(0, 0))
        self.key_0.setMaximumSize(QtCore.QSize(25, 25))
        self.key_0.setObjectName("key_0")
        self.horizontalLayout.addWidget(self.key_0)
        self.btnBackspace = QtWidgets.QPushButton(menuKeyBoard)
        self.btnBackspace.setMinimumSize(QtCore.QSize(0, 0))
        self.btnBackspace.setMaximumSize(QtCore.QSize(50, 25))
        self.btnBackspace.setObjectName("btnBackspace")
        self.horizontalLayout.addWidget(self.btnBackspace)
        self.btnQuit = QtWidgets.QPushButton(menuKeyBoard)
        self.btnQuit.setMinimumSize(QtCore.QSize(0, 0))
        self.btnQuit.setMaximumSize(QtCore.QSize(25, 25))
        self.btnQuit.setObjectName("btnQuit")
        self.horizontalLayout.addWidget(self.btnQuit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCapsLock = QtWidgets.QPushButton(menuKeyBoard)
        self.btnCapsLock.setMaximumSize(QtCore.QSize(65, 25))
        self.btnCapsLock.setObjectName("btnCapsLock")
        self.horizontalLayout_2.addWidget(self.btnCapsLock)
        self.pushButton_27 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_27.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_2.addWidget(self.pushButton_27)
        self.pushButton_26 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_26.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_2.addWidget(self.pushButton_26)
        self.pushButton_25 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_25.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_2.addWidget(self.pushButton_25)
        self.pushButton_24 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_24.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_2.addWidget(self.pushButton_24)
        self.pushButton_23 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_23.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_2.addWidget(self.pushButton_23)
        self.pushButton_22 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_22.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_2.addWidget(self.pushButton_22)
        self.pushButton_21 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_21.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_2.addWidget(self.pushButton_21)
        self.pushButton_20 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_20.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_2.addWidget(self.pushButton_20)
        self.pushButton_19 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_19.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_2.addWidget(self.pushButton_19)
        self.pushButton_18 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_18.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_2.addWidget(self.pushButton_18)
        self.btnShift = QtWidgets.QPushButton(menuKeyBoard)
        self.btnShift.setMaximumSize(QtCore.QSize(50, 25))
        self.btnShift.setObjectName("btnShift")
        self.horizontalLayout_2.addWidget(self.btnShift)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(8, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_2.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_3.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_4.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_5.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_6.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_7.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_8.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_9.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_10.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_11.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_12.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_13.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(8, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_14 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_14.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_4.addWidget(self.pushButton_14)
        self.pushButton_16 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_16.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_4.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_17.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_4.addWidget(self.pushButton_17)
        self.pushButton_28 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_28.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_4.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_29.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_4.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_30.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_4.addWidget(self.pushButton_30)
        self.pushButton_31 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_31.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_4.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_32.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_4.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_33.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_4.addWidget(self.pushButton_33)
        self.pushButton_34 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_34.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_4.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_35.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_4.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_36.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_4.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(menuKeyBoard)
        self.pushButton_37.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_4.addWidget(self.pushButton_37)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(menuKeyBoard)
        QtCore.QMetaObject.connectSlotsByName(menuKeyBoard)

    def retranslateUi(self, menuKeyBoard):
        _translate = QtCore.QCoreApplication.translate
        menuKeyBoard.setWindowTitle(_translate("menuKeyBoard", "Dialog"))
        self.pushButton_15.setText(_translate("menuKeyBoard", "`~"))
        self.key_1.setText(_translate("menuKeyBoard", "1!"))
        self.key_2.setText(_translate("menuKeyBoard", "2@"))
        self.key_3.setText(_translate("menuKeyBoard", "3#"))
        self.key_4.setText(_translate("menuKeyBoard", "4$"))
        self.key_5.setText(_translate("menuKeyBoard", "5%"))
        self.key_6.setText(_translate("menuKeyBoard", "6^"))
        self.key_7.setText(_translate("menuKeyBoard", "7&"))
        self.key_8.setText(_translate("menuKeyBoard", "8*"))
        self.key_9.setText(_translate("menuKeyBoard", "9("))
        self.key_0.setText(_translate("menuKeyBoard", "0)"))
        self.btnBackspace.setText(_translate("menuKeyBoard", "←"))
        self.btnQuit.setText(_translate("menuKeyBoard", "×"))
        self.btnCapsLock.setText(_translate("menuKeyBoard", "Caps Lock"))
        self.pushButton_27.setText(_translate("menuKeyBoard", "-_"))
        self.pushButton_26.setText(_translate("menuKeyBoard", "=+"))
        self.pushButton_25.setText(_translate("menuKeyBoard", "[{"))
        self.pushButton_24.setText(_translate("menuKeyBoard", "]}"))
        self.pushButton_23.setText(_translate("menuKeyBoard", "\\|"))
        self.pushButton_22.setText(_translate("menuKeyBoard", ";:"))
        self.pushButton_21.setText(_translate("menuKeyBoard", "\'\""))
        self.pushButton_20.setText(_translate("menuKeyBoard", ",<"))
        self.pushButton_19.setText(_translate("menuKeyBoard", ".>"))
        self.pushButton_18.setText(_translate("menuKeyBoard", "/?"))
        self.btnShift.setText(_translate("menuKeyBoard", "Shift"))
        self.pushButton.setText(_translate("menuKeyBoard", "a"))
        self.pushButton_2.setText(_translate("menuKeyBoard", "b"))
        self.pushButton_3.setText(_translate("menuKeyBoard", "c"))
        self.pushButton_4.setText(_translate("menuKeyBoard", "d"))
        self.pushButton_5.setText(_translate("menuKeyBoard", "e"))
        self.pushButton_6.setText(_translate("menuKeyBoard", "f"))
        self.pushButton_7.setText(_translate("menuKeyBoard", "g"))
        self.pushButton_8.setText(_translate("menuKeyBoard", "h"))
        self.pushButton_9.setText(_translate("menuKeyBoard", "i"))
        self.pushButton_10.setText(_translate("menuKeyBoard", "j"))
        self.pushButton_11.setText(_translate("menuKeyBoard", "k"))
        self.pushButton_12.setText(_translate("menuKeyBoard", "l"))
        self.pushButton_13.setText(_translate("menuKeyBoard", "m"))
        self.pushButton_14.setText(_translate("menuKeyBoard", "n"))
        self.pushButton_16.setText(_translate("menuKeyBoard", "o"))
        self.pushButton_17.setText(_translate("menuKeyBoard", "p"))
        self.pushButton_28.setText(_translate("menuKeyBoard", "q"))
        self.pushButton_29.setText(_translate("menuKeyBoard", "r"))
        self.pushButton_30.setText(_translate("menuKeyBoard", "s"))
        self.pushButton_31.setText(_translate("menuKeyBoard", "t"))
        self.pushButton_32.setText(_translate("menuKeyBoard", "u"))
        self.pushButton_33.setText(_translate("menuKeyBoard", "v"))
        self.pushButton_34.setText(_translate("menuKeyBoard", "w"))
        self.pushButton_35.setText(_translate("menuKeyBoard", "x"))
        self.pushButton_36.setText(_translate("menuKeyBoard", "y"))
        self.pushButton_37.setText(_translate("menuKeyBoard", "z"))

