# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Login.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(430, 330)
        Login.setMinimumSize(QtCore.QSize(430, 330))
        Login.setMaximumSize(QtCore.QSize(430, 330))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Login)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(338, 0, 92, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnSetting = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSetting.setMinimumSize(QtCore.QSize(30, 30))
        self.btnSetting.setMaximumSize(QtCore.QSize(30, 30))
        self.btnSetting.setText("")
        self.btnSetting.setObjectName("btnSetting")
        self.horizontalLayout_6.addWidget(self.btnSetting)
        self.btnMini = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnMini.setMinimumSize(QtCore.QSize(30, 30))
        self.btnMini.setMaximumSize(QtCore.QSize(30, 30))
        self.btnMini.setObjectName("btnMini")
        self.horizontalLayout_6.addWidget(self.btnMini)
        self.btnExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnExit.setMinimumSize(QtCore.QSize(30, 30))
        self.btnExit.setMaximumSize(QtCore.QSize(30, 30))
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_6.addWidget(self.btnExit)
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 430, 125))
        self.label_2.setMinimumSize(QtCore.QSize(0, 115))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(1, 1, 84, 32))
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.frameGlobal = QtWidgets.QFrame(Login)
        self.frameGlobal.setGeometry(QtCore.QRect(0, -1, 430, 331))
        self.frameGlobal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGlobal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGlobal.setObjectName("frameGlobal")
        self.btnSignIn = QtWidgets.QPushButton(self.frameGlobal)
        self.btnSignIn.setGeometry(QtCore.QRect(1, 300, 75, 30))
        self.btnSignIn.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSignIn.setMaximumSize(QtCore.QSize(75, 20))
        self.btnSignIn.setObjectName("btnSignIn")
        self.btnQRcode = QtWidgets.QPushButton(self.frameGlobal)
        self.btnQRcode.setGeometry(QtCore.QRect(397, 300, 25, 25))
        self.btnQRcode.setStatusTip("")
        self.btnQRcode.setText("")
        self.btnQRcode.setObjectName("btnQRcode")
        self.labUserImg = QtWidgets.QLabel(self.frameGlobal)
        self.labUserImg.setGeometry(QtCore.QRect(177, 90, 71, 71))
        self.labUserImg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labUserImg.setText("")
        self.labUserImg.setScaledContents(True)
        self.labUserImg.setObjectName("labUserImg")
        self.btnAddUser = QtWidgets.QPushButton(self.frameGlobal)
        self.btnAddUser.setGeometry(QtCore.QRect(203, 102, 45, 45))
        self.btnAddUser.setMinimumSize(QtCore.QSize(45, 45))
        self.btnAddUser.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnAddUser.setFont(font)
        self.btnAddUser.setObjectName("btnAddUser")
        self.btnLoginSingle = QtWidgets.QPushButton(self.frameGlobal)
        self.btnLoginSingle.setGeometry(QtCore.QRect(0, 292, 95, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLoginSingle.setFont(font)
        self.btnLoginSingle.setObjectName("btnLoginSingle")
        self.frame = QtWidgets.QFrame(self.frameGlobal)
        self.frame.setGeometry(QtCore.QRect(90, 160, 255, 150))
        self.frame.setMinimumSize(QtCore.QSize(255, 150))
        self.frame.setMaximumSize(QtCore.QSize(255, 150))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameInput = QtWidgets.QFrame(self.frame)
        self.frameInput.setMinimumSize(QtCore.QSize(255, 75))
        self.frameInput.setMaximumSize(QtCore.QSize(255, 75))
        self.frameInput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInput.setObjectName("frameInput")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameInput)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboUserId = QtWidgets.QComboBox(self.frameInput)
        self.comboUserId.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboUserId.setFont(font)
        self.comboUserId.setEditable(True)
        self.comboUserId.setMaxVisibleItems(5)
        self.comboUserId.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboUserId.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboUserId.setIconSize(QtCore.QSize(30, 30))
        self.comboUserId.setObjectName("comboUserId")
        self.verticalLayout_2.addWidget(self.comboUserId)
        self.lEditPassword = QtWidgets.QLineEdit(self.frameInput)
        self.lEditPassword.setMinimumSize(QtCore.QSize(0, 30))
        self.lEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lEditPassword.setDragEnabled(False)
        self.lEditPassword.setReadOnly(False)
        self.lEditPassword.setObjectName("lEditPassword")
        self.verticalLayout_2.addWidget(self.lEditPassword)
        self.verticalLayout.addWidget(self.frameInput)
        self.frameLogin = QtWidgets.QFrame(self.frame)
        self.frameLogin.setMinimumSize(QtCore.QSize(255, 75))
        self.frameLogin.setMaximumSize(QtCore.QSize(255, 75))
        self.frameLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogin.setObjectName("frameLogin")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameLogin)
        self.verticalLayout_4.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxAotuLogin = QtWidgets.QCheckBox(self.frameLogin)
        self.checkBoxAotuLogin.setObjectName("checkBoxAotuLogin")
        self.horizontalLayout_2.addWidget(self.checkBoxAotuLogin)
        self.checkBoxKeepPassword = QtWidgets.QCheckBox(self.frameLogin)
        self.checkBoxKeepPassword.setObjectName("checkBoxKeepPassword")
        self.horizontalLayout_2.addWidget(self.checkBoxKeepPassword)
        self.btnFindBack = QtWidgets.QPushButton(self.frameLogin)
        self.btnFindBack.setMinimumSize(QtCore.QSize(0, 20))
        self.btnFindBack.setMaximumSize(QtCore.QSize(58, 20))
        self.btnFindBack.setObjectName("btnFindBack")
        self.horizontalLayout_2.addWidget(self.btnFindBack)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.btnLogin = QtWidgets.QPushButton(self.frameLogin)
        self.btnLogin.setMinimumSize(QtCore.QSize(253, 35))
        self.btnLogin.setMaximumSize(QtCore.QSize(253, 35))
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout_4.addWidget(self.btnLogin)
        self.verticalLayout.addWidget(self.frameLogin)
        self.frameAdduser = QtWidgets.QFrame(self.frame)
        self.frameAdduser.setMinimumSize(QtCore.QSize(255, 75))
        self.frameAdduser.setMaximumSize(QtCore.QSize(255, 75))
        self.frameAdduser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAdduser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAdduser.setObjectName("frameAdduser")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameAdduser)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setSpacing(30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnAdd = QtWidgets.QPushButton(self.frameAdduser)
        self.btnAdd.setMinimumSize(QtCore.QSize(110, 35))
        self.btnAdd.setMaximumSize(QtCore.QSize(110, 35))
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_5.addWidget(self.btnAdd)
        self.btnCancel = QtWidgets.QPushButton(self.frameAdduser)
        self.btnCancel.setMinimumSize(QtCore.QSize(110, 35))
        self.btnCancel.setMaximumSize(QtCore.QSize(110, 35))
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_5.addWidget(self.btnCancel)
        self.horizontalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.frameAdduser)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.btnSignIn.raise_()
        self.btnQRcode.raise_()
        self.btnAddUser.raise_()
        self.labUserImg.raise_()
        self.btnLoginSingle.raise_()
        self.frame.raise_()
        self.frameError = QtWidgets.QFrame(Login)
        self.frameError.setGeometry(QtCore.QRect(0, 330, 430, 20))
        self.frameError.setMinimumSize(QtCore.QSize(430, 20))
        self.frameError.setMaximumSize(QtCore.QSize(430, 20))
        self.frameError.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameError.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameError.setObjectName("frameError")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameError)
        self.horizontalLayout_3.setContentsMargins(2, 0, 1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labErrorImg = QtWidgets.QLabel(self.frameError)
        self.labErrorImg.setMinimumSize(QtCore.QSize(15, 15))
        self.labErrorImg.setMaximumSize(QtCore.QSize(18, 18))
        self.labErrorImg.setText("")
        self.labErrorImg.setObjectName("labErrorImg")
        self.horizontalLayout_3.addWidget(self.labErrorImg)
        self.labErrorInfo = QtWidgets.QLabel(self.frameError)
        self.labErrorInfo.setObjectName("labErrorInfo")
        self.horizontalLayout_3.addWidget(self.labErrorInfo)
        self.btnError = QtWidgets.QPushButton(self.frameError)
        self.btnError.setMaximumSize(QtCore.QSize(15, 18))
        self.btnError.setText("")
        self.btnError.setObjectName("btnError")
        self.horizontalLayout_3.addWidget(self.btnError)
        self.frameQRcode = QtWidgets.QFrame(Login)
        self.frameQRcode.setGeometry(QtCore.QRect(40, 0, 360, 330))
        self.frameQRcode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameQRcode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameQRcode.setObjectName("frameQRcode")
        self.frameQRcodeUpdata = QtWidgets.QFrame(self.frameQRcode)
        self.frameQRcodeUpdata.setGeometry(QtCore.QRect(0, 48, 360, 175))
        self.frameQRcodeUpdata.setMinimumSize(QtCore.QSize(360, 175))
        self.frameQRcodeUpdata.setMaximumSize(QtCore.QSize(360, 175))
        self.frameQRcodeUpdata.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameQRcodeUpdata.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameQRcodeUpdata.setObjectName("frameQRcodeUpdata")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameQRcodeUpdata)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnFrameQRcodeUpdata = QtWidgets.QPushButton(self.frameQRcodeUpdata)
        self.btnFrameQRcodeUpdata.setMinimumSize(QtCore.QSize(129, 129))
        self.btnFrameQRcodeUpdata.setMaximumSize(QtCore.QSize(129, 129))
        self.btnFrameQRcodeUpdata.setText("")
        self.btnFrameQRcodeUpdata.setObjectName("btnFrameQRcodeUpdata")
        self.horizontalLayout_7.addWidget(self.btnFrameQRcodeUpdata)
        self.btnFrameQRcodeUrl = QtWidgets.QPushButton(self.frameQRcodeUpdata)
        self.btnFrameQRcodeUrl.setMinimumSize(QtCore.QSize(165, 175))
        self.btnFrameQRcodeUrl.setMaximumSize(QtCore.QSize(165, 175))
        self.btnFrameQRcodeUrl.setText("")
        self.btnFrameQRcodeUrl.setObjectName("btnFrameQRcodeUrl")
        self.horizontalLayout_7.addWidget(self.btnFrameQRcodeUrl)
        self.btnFrameQRcodeBack = QtWidgets.QPushButton(self.frameQRcode)
        self.btnFrameQRcodeBack.setGeometry(QtCore.QRect(52, 271, 253, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFrameQRcodeBack.sizePolicy().hasHeightForWidth())
        self.btnFrameQRcodeBack.setSizePolicy(sizePolicy)
        self.btnFrameQRcodeBack.setMinimumSize(QtCore.QSize(253, 35))
        self.btnFrameQRcodeBack.setMaximumSize(QtCore.QSize(253, 35))
        self.btnFrameQRcodeBack.setObjectName("btnFrameQRcodeBack")
        self.frame_4 = QtWidgets.QFrame(self.frameQRcode)
        self.frame_4.setGeometry(QtCore.QRect(40, 226, 301, 20))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labFrameQRcodeErrorImg = QtWidgets.QLabel(self.frame_4)
        self.labFrameQRcodeErrorImg.setMinimumSize(QtCore.QSize(15, 15))
        self.labFrameQRcodeErrorImg.setMaximumSize(QtCore.QSize(15, 15))
        self.labFrameQRcodeErrorImg.setText("")
        self.labFrameQRcodeErrorImg.setObjectName("labFrameQRcodeErrorImg")
        self.horizontalLayout_4.addWidget(self.labFrameQRcodeErrorImg)
        self.labFrameQRcodeInfo = QtWidgets.QLabel(self.frame_4)
        self.labFrameQRcodeInfo.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labFrameQRcodeInfo.setFont(font)
        self.labFrameQRcodeInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labFrameQRcodeInfo.setOpenExternalLinks(True)
        self.labFrameQRcodeInfo.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.labFrameQRcodeInfo.setObjectName("labFrameQRcodeInfo")
        self.horizontalLayout_4.addWidget(self.labFrameQRcodeInfo)
        self.label_2.raise_()
        self.frameGlobal.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_3.raise_()
        self.frameError.raise_()
        self.frameQRcode.raise_()

        self.retranslateUi(Login)
        self.btnExit.clicked.connect(Login.close)
        self.btnMini.clicked.connect(Login.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.btnSetting.setToolTip(_translate("Login", "设置"))
        self.btnMini.setToolTip(_translate("Login", "最小化"))
        self.btnMini.setText(_translate("Login", "—"))
        self.btnExit.setToolTip(_translate("Login", "关闭"))
        self.btnExit.setText(_translate("Login", "×"))
        self.btnSignIn.setText(_translate("Login", "注册账号"))
        self.btnQRcode.setToolTip(_translate("Login", "二维码登录"))
        self.btnAddUser.setToolTip(_translate("Login", "多账号登录"))
        self.btnAddUser.setText(_translate("Login", "+"))
        self.btnLoginSingle.setText(_translate("Login", "< 单账号登录"))
        self.checkBoxAotuLogin.setText(_translate("Login", "自动登录"))
        self.checkBoxKeepPassword.setText(_translate("Login", "记住密码"))
        self.btnFindBack.setText(_translate("Login", "找回密码"))
        self.btnLogin.setText(_translate("Login", "登录"))
        self.btnAdd.setText(_translate("Login", "添加"))
        self.btnCancel.setText(_translate("Login", "取消"))
        self.labErrorInfo.setText(_translate("Login", "你已在QQ登录了XXX，不能重复登录。"))
        self.btnFrameQRcodeBack.setText(_translate("Login", "返回"))
        self.labFrameQRcodeInfo.setText(_translate("Login", "<style> a {text-decoration: none} </style> 用<a href=\"http://im.qq.com/mobileqq\">QQ手机版</a>扫描二维码安全登录。<a href=\"https://aq.qq.com/cn2/index\">手机丢失？</a>"))

