# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Login.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayout = QtWidgets.QFormLayout(self.page)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(30, 0, 30, 0)
        self.formLayout.setHorizontalSpacing(2)
        self.formLayout.setVerticalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditId = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditId.sizePolicy().hasHeightForWidth())
        self.lineEditId.setSizePolicy(sizePolicy)
        self.lineEditId.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditId.setFont(font)
        self.lineEditId.setStyleSheet("color: rgb(85, 85, 255);")
        self.lineEditId.setMaxLength(8)
        self.lineEditId.setObjectName("lineEditId")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditId)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditPswd = QtWidgets.QLineEdit(self.page)
        self.lineEditPswd.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditPswd.setFont(font)
        self.lineEditPswd.setStyleSheet("color: rgb(85, 85, 255);")
        self.lineEditPswd.setMaxLength(15)
        self.lineEditPswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPswd.setObjectName("lineEditPswd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditPswd)
        self.btnGoSignIn = QtWidgets.QPushButton(self.page)
        self.btnGoSignIn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGoSignIn.setFont(font)
        self.btnGoSignIn.setObjectName("btnGoSignIn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.btnGoSignIn)
        self.btnLogin = QtWidgets.QPushButton(self.page)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnLogin)
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEditPort = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPort.sizePolicy().hasHeightForWidth())
        self.lineEditPort.setSizePolicy(sizePolicy)
        self.lineEditPort.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditPort.setFont(font)
        self.lineEditPort.setStyleSheet("color: rgb(195, 0, 0);")
        self.lineEditPort.setMaxLength(8)
        self.lineEditPort.setObjectName("lineEditPort")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditPort)
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEditIp = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditIp.sizePolicy().hasHeightForWidth())
        self.lineEditIp.setSizePolicy(sizePolicy)
        self.lineEditIp.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditIp.setFont(font)
        self.lineEditIp.setStyleSheet("color: rgb(195, 0, 0);")
        self.lineEditIp.setMaxLength(15)
        self.lineEditIp.setObjectName("lineEditIp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditIp)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(15)
        self.page_2.setFont(font)
        self.page_2.setObjectName("page_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.page_2)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setContentsMargins(30, 0, 30, 0)
        self.formLayout_2.setHorizontalSpacing(2)
        self.formLayout_2.setVerticalSpacing(8)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 40))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEditSignInId = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSignInId.sizePolicy().hasHeightForWidth())
        self.lineEditSignInId.setSizePolicy(sizePolicy)
        self.lineEditSignInId.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditSignInId.setFont(font)
        self.lineEditSignInId.setObjectName("lineEditSignInId")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditSignInId)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditNickname = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNickname.sizePolicy().hasHeightForWidth())
        self.lineEditNickname.setSizePolicy(sizePolicy)
        self.lineEditNickname.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditNickname.setFont(font)
        self.lineEditNickname.setObjectName("lineEditNickname")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditNickname)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditSignInPswd2 = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSignInPswd2.sizePolicy().hasHeightForWidth())
        self.lineEditSignInPswd2.setSizePolicy(sizePolicy)
        self.lineEditSignInPswd2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditSignInPswd2.setFont(font)
        self.lineEditSignInPswd2.setObjectName("lineEditSignInPswd2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditSignInPswd2)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEditSignInPswd = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSignInPswd.sizePolicy().hasHeightForWidth())
        self.lineEditSignInPswd.setSizePolicy(sizePolicy)
        self.lineEditSignInPswd.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditSignInPswd.setFont(font)
        self.lineEditSignInPswd.setObjectName("lineEditSignInPswd")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditSignInPswd)
        self.btnBack = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBack.sizePolicy().hasHeightForWidth())
        self.btnBack.setSizePolicy(sizePolicy)
        self.btnBack.setMinimumSize(QtCore.QSize(0, 40))
        self.btnBack.setObjectName("btnBack")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.btnBack)
        self.btnSignIn = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSignIn.sizePolicy().hasHeightForWidth())
        self.btnSignIn.setSizePolicy(sizePolicy)
        self.btnSignIn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.btnSignIn.setFont(font)
        self.btnSignIn.setObjectName("btnSignIn")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnSignIn)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Login)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "客户端登录"))
        self.label.setText(_translate("Login", "账号："))
        self.lineEditId.setPlaceholderText(_translate("Login", "请输入账号"))
        self.label_2.setText(_translate("Login", "密码："))
        self.lineEditPswd.setPlaceholderText(_translate("Login", "请输入密码"))
        self.btnGoSignIn.setText(_translate("Login", "注册"))
        self.btnLogin.setText(_translate("Login", "登录"))
        self.label_9.setText(_translate("Login", "端口："))
        self.lineEditPort.setPlaceholderText(_translate("Login", "请输入port端口"))
        self.label_10.setText(_translate("Login", "地址："))
        self.lineEditIp.setInputMask(_translate("Login", "000.000.000.000"))
        self.lineEditIp.setPlaceholderText(_translate("Login", "请输入ip地址"))
        self.label_6.setText(_translate("Login", "账号："))
        self.lineEditSignInId.setPlaceholderText(_translate("Login", "请输入数字或字母组合"))
        self.label_3.setText(_translate("Login", "昵称："))
        self.lineEditNickname.setPlaceholderText(_translate("Login", "最多8个字符"))
        self.label_4.setText(_translate("Login", "密码："))
        self.lineEditSignInPswd2.setPlaceholderText(_translate("Login", "最多15位"))
        self.label_5.setText(_translate("Login", "确认："))
        self.lineEditSignInPswd.setPlaceholderText(_translate("Login", "再次输入密码"))
        self.btnBack.setText(_translate("Login", "返回"))
        self.btnSignIn.setText(_translate("Login", "注册"))
